### ISSUE TITLE
$vpf missing and $vpr, $vpt, $vpd links are broken

### ISSUE THREAD

**Issue by Khalinda** [openscad/openscad.github.com#99]
With the addition of the $vpf variable in OpenSCAD 2021.1, the HTML anchor has changed from "#$vpr,_$vpt_and_$vpd to "#$vpr,_$vpt,_$vpf_and_$vpd".

**Comment by t-paul** [comment]
Fixed for cheatsheet (both release & snapshot). Please reopen in case there's other places I missed.

**Comment by Khalinda** [comment]
Thanks t-paul...  The links for $vpr, $vpt and $vpd appear to be correct now, but I still don't see a link for $vpf.

Since you asked, I clicked on all of the links on the cheatsheet:
1.  PI has a link to a Wikipedia article,  Perhaps a link to "General/#Values_and_Data_Types" or "General/#Numbers" would also be helpful.
2. The link to "children" (NOT "$children") is broken.  The link appears to be correct, but the header on the target page doesn't have an HTML anchor defined.

**Comment by t-paul** [comment]
Oops, I added `$vpf` only to the snapshot cheatsheet even though the documentation clearly states 2021.01. Fixed now.

Sorry, I did not mean to ask you to validate everything, I mentioned the 2 cheatsheet pages in case you found the broken $vpf link in some other page.

But thanks a lot for looking through the links:

1) `PI` - good idea, I've linked to "#Numbers" as that subsection does mention PI specifically

2) `children()` - fixed in both release and snapshot cheatsheet
